routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('source', 'SourceController');
    Route::resource('category', 'CategoryController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 * @package App
 */
class Category extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function sources()
    {
        return $this->belongsToMany(Source::class, 'source_category');
    }
}

app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Feed
 * @package App
 */
class Feed extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['title', 'description', 'link', 'source_id', 'published_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function source()
    {
        return $this->belongsTo(Source::class);
    }
}

app/Source.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Source
 * @package App
 */
class Source extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['title', 'name', 'url', 'rss_url'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function feeds()
    {
        return $this->hasMany(Feed::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 * @package App
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Source;
use Illuminate\Http\Request;

/**
 * Class CategoryController
 * @package App\Http\Controllers
 */
class CategoryController extends Controller
{
    /**
     * @return mixed
     */
    protected function index()
    {
        $categories = Category::all();

        return view('categories')->with(compact('categories'));
    }

    /**
     * @param $id
     * @return mixed
     */
    protected function view($id)
    {
        return Category::find($id);
    }

    /**
     * @return mixed
     */
    protected function create()
    {
        $sources = Source::all();

        return view('category.create-or-update')->with(compact('sources'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'category_id' => 'exists:categories,id'
        ]);

        if ($request->has('category_id')) {
            return $this->update($request, $request->get('category_id'));
        }

        $category = Category::create($request->only([
            'name'
        ]));

        $category->sources()->sync($request->get('sources', []));

        return redirect()->route('category.index');
    }

    /**
     * @param $id
     * @return mixed
     */
    protected function edit($id)
    {
        $category = Category::with('sources')->find($id);

        if ($category) {
            $sources = Source::all();

            return view('category.create-or-update')->with(compact('category', 'sources'));
        }
        return redirect()->route('category.index');
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $category = Category::find($id);

        if ($category) {
            $category->update($request->only([
                'name'
            ]));
            $category->sources()->sync($request->get('sources', []));
        }

        return redirect()->route('category.index');
    }

    /**
     * @param $id
     * @return int
     */
    protected function destroy($id)
    {
        return Category::destroy($id);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Feed;
use Illuminate\Http\Request;

/**
 * Class FeedController
 * @package App\Http\Controllers
 */
class FeedController extends Controller
{
    /**
     * @param null $category_id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Database\Eloquent\Collection|\Symfony\Component\HttpFoundation\Response|static[]
     */
    protected function feed($category_id = null)
    {
        if ($category_id) {
            $category = Category::with('sources')->find($category_id);

            if (!$category) {
                return response(400);
            }

            $query = Feed::whereIn('source_id', $category->sources->pluck('id'));
        } else {
            $query = Feed::query();
        }

        return $query->with('source')->orderBy('published_at', 'desc')->limit(30)->get();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

/**
 * Class HomeController
 * @package App\Http\Controllers
 */
class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     */
    public function index()
    {
        $categories = Category::all();

        return view('welcome')->with(compact('categories'));
    }
}

app/Http/Controllers/SourceController.php
<?php

namespace App\Http\Controllers;

use App\Source;
use Illuminate\Http\Request;

/**
 * Class SourceController
 * @package App\Http\Controllers
 */
class SourceController extends Controller
{
    /**
     * @return mixed
     */
    public function index()
    {
        $sources = Source::all();

        return view('source-list')->with(compact('sources'));
    }

    /**
     * @param Request $request
     * @return \App\Source
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'name' => 'required',
            'url' => 'required',
            'rss_url' => 'required'
        ]);

        $source = Source::create($request->only(['title', 'name', 'url', 'rss_url']));

        return $source;
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'name' => 'required',
            'url' => 'required',
            'rss_url' => 'required'
        ]);

        $source = Source::find($id);

        if (!$source) {
            return response("Invalid ID", 400);
        }

        $source->update($request->only(['title', 'name', 'url', 'rss_url']));

        return $source;
    }

    /**
     * @param $id
     * @return string
     */
    public function destroy($id)
    {
        Source::destroy($id);

        return 'OK';
    }
}

resources/views/categories.blade.php
@extends ('layouts.app')

@section ('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Categories
                        <a href="{{ route('category.create') }}" class="btn btn-xs btn-primary"
                           style="margin-left: 10px">
                            add new
                        </a>
                    </div>

                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th width="150px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-default"
                                           href="{{ route('category.edit', ['id' => $category->id]) }}">
                                            Edit
                                        </a>
                                        <delete-button url="{{ route('category.destroy', ['id' => $category->id]) }}"
                                                       classes="btn btn-sm btn-danger">
                                            Delete
                                        </delete-button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/category/create-or-update.blade.php
@extends ('layouts.app')

@section ('content')

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create new category
            </div>

            <div class="panel-body">
                <form action="{{ route('category.store') }}"
                      method="POST">
                    {!! csrf_field() !!}

                    @if(isset($category))
                        <input type="hidden" name="category_id" value="{{ $category->id }}">
                    @endif

                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" name="name" class="form-control"
                               value="{{ isset($category) ? $category->name : old('name') }}">
                    </div>
                    <div class="form-group">
                        <label>Feeds:</label>
                        <select multiple name="sources[]" class="form-control">
                            @foreach($sources as $source)
                                <option value="{{ $source->id }}" @if(isset($category)) {{ $category->sources->where('id', $source->id)->count() ? 'selected' : '' }} @endif>
                                    {{ $source->title }} - {{ $source->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit"
                            class="btn btn-primary">{{ isset($category) ? 'Update category' : 'Create category' }}</button>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    @if(Auth::check())
                        <li><a href="{{ route('source.index') }}">Sources List</a></li>
                        <li><a href="{{ route('category.index') }}">Categories</a></li>
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')
</div>

<!-- Scripts -->
<script src="/js/app.js"></script>
</body>
</html>

resources/views/source-list.blade.php
@extends ('layouts.app')

@section ('content')

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Feed list</div>

            <div class="panel-body">
                <data-table
                        name="source"
                        items="{{ $sources->toJson() }}"
                        columns='[
                                    { "title": "Title", "prop": "title" },
                                    { "title": "Name", "prop": "name" },
                                    { "title": "URL", "prop": "url", "isLink": true },
                                    { "title": "RSS URL", "prop": "rss_url", "isLink": true }
                                ]'
                ></data-table>
            </div>
        </div>
    </div>

@endsection